### ISSUE TITLE
Is the signal in an Output always originated from related Receivers?

### ISSUE THREAD

**Issue by N-Nagorny** [AMWA-TV/nmos-sink-metadata-processing#118]
Section 'Status of Output' dictates:

> An Output has the following states that describe the signal at this Output:
> - `no_signal` when this Output is not producing any signal to a downstream counterpart (e.g. if the Output has associated Receivers, it may mean that one or more of these Receivers do not have a compliant incoming stream).
> - `signal_present` when the signal is present and stable.
> 
> Debug information expressed through `debug` property SHOULD assist `no_signal` state and MAY assist the other states.

It doesn't specify if the signal in question is produced by related Receivers or by something in the middle between them and the Output. We may want to describe these two cases separately. For instance, by adding the third, `default_signal` state.

**Comment by alabou** [comment]
The text "(e.g. if the Output has associated Receivers, it may mean that one or more of these Receivers do not have a compliant incoming stream)" seemed to indicate that no_signal and signal_present were referring to a signal originating from the Receiver.

The test plan actually only look at the state being or not "signal_present". Adding a "default_signal" state to indicate that without a signal from the Receiver, a default signal is produced on the output would not affect the test suite. Using such "default_signal" state should be optional to the devices because not all devices may support auto-generating a default signal.

Note that the same concept of a default signal applies to the Sender side ... except that there is no need for a default_signal state for an input. The input will indicate no_signal but a Controller may observe that the Sender state is for example "unconstrained" or "constrained", meaning that the Sender has a signal (default) to transmit.
