### ISSUE TITLE
Media Profiles and Prefered Mode

### ISSUE THREAD

**Issue by prince-chrismc** [AMWA-TV/nmos-sink-metadata-processing#31]
One important attribute in an EDID is the prefered mode. We have documented this in bcp-005-01 but it does not carry over to the Media Profiles.

When a `PUT /media-profiles` occurs how does the sender know which corresponds to the "prefered mode"?

**Comment by cristian-recoseanu** [comment]
And on top of this. Should we clarify that it is the responsability of the source/sender to use the best quality profile it can support out of the available media profiles array? We can turn this into another issue but they are related somehow.

**Comment by prince-chrismc** [comment]
🤔 

https://github.com/AMWA-TV/nmos-sink-metadata-processing/pull/12/files#diff-e88d03489d1f66312bb18bb73cdd0fd256d90d662525d17dfd2f546ba6b71c58R7

> let the underlying implementation to choose exactly which format from the set it will use. A client can pass a single Media Profile to specify the exact format.

Is this enough?

**Comment by N-Nagorny** [comment]
I agree with Chris. It should be chosen on the Controller side. In this case a user can leave the best quality profile but also a profile with the least expected bit rate for instance or consider any other factor important to him.

I created a PR draft #35.

**Comment by cristian-recoseanu** [comment]
I disagree. I think the controller does not have the operating modes of the sender to know which (best) profile will be supported. I think the best workflow is to pass all compatible profiles from receivers (potentially with a preference property) and let the sender choose the best quality profile out of all the options.
Passing a single Media Profile will not work in practice because if you don't know if the sender can accomodate that in advance are you meant to try 50 profiles 1 at a time?
