### ISSUE TITLE
EDID endpoints

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-sink-metadata-processing#79]
As I understand it, Inputs and Outputs basically define their capabilities and active configuration in terms of Constraint Sets.

In order to make this spec even more useful going forward, have you considered changing the name of the mandatory _/edid_ endpoints into something more neutral, and using `Content-Type` and `Accept` request/response headers to indicate the data type?

This would follow the model adopted by IS-05, which has _/transportfile_ (and uses `application/sdp`) rather than e.g. _/sdp_.

**Comment by alabou** [comment]
Capabilities and Constraints apply to Receivers and Senders ... not to Input or Outputs. An Output may "influence" the Capabilities of Receivers associated with such Output. The Constraints of a Sender may "influence" such Sender associated Inputs.

The group have considered adding other metadata types at the same level as the "edid" endpoint and having a similar "*_support" property. The EDID metadata type is a well known concept. Similarly other "well known" metadata concepts could be added in the future. I'm not sure there exist an application/edid content-type, that's why it is specified as application/octet-stream. It may not be easy to add such content-type ... Also this approach would prevent the simultaneous use of multiple metadata representations for a given Output/Input. I think it is worth review this issue in the group.

**Comment by N-Nagorny** [comment]
I would like to replace `/inputs/{inputId}/edid` with `/inputs/{inputId}/metadatafile` but it's not clear for me how to deal with `edid_support` property of Input/Output. If we can constrain them to support only a single metadata file format at a time, then it should be OK to replace `edid_support` with `metadatafile_support` and add a property `metadatafile_type`.

**Comment by alabou** [comment]
I think we should not close the possibility to have simultaneous metadata formats supported. This is why I think the actual properties <metadata-format-name> and <metadata-format-name>_support are doing the job. Actually <metadata-format-name> is edid but more could be added in the future. Also in IS-11 we have the concepts of base and effective edid for the sender and simply edid for the receiver. It is not clear if those concepts would also apply to another metadata format, making it difficult to consider "generic" metadata support.

**Comment by garethsb** [comment]
I completely agree the possibility of multiple metadata formats should be taken into consideration, and would subsume my concerns about being limited to EDID. If v1.0 of the spec can be designed to accommodate this without the need for a version-up that would be perfect, but I appreciate this may fall outside the goals and remit of the current activity group.

**Comment by N-Nagorny** [comment]
This issue is beyond of the v1.0 scope so we're closing it.
