### ISSUE TITLE
Inputs and Outputs

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-sink-metadata-processing#80]
Input and Output are fine words, but the perspective from which they are to be interpreted needs to be very clear.

If I've understood correctly:

* In IS-11, Inputs are associated with a Sender, and a Receiver is associated with Outputs.
* In IS-08, Receivers (or Sources...) are associated with Inputs, and Outputs are associated with (Sources -> Flows ->)Senders.

This difference is jarring. If the perspectives can't be aligned, it needs a good explanation up front, please.

**Comment by alabou** [comment]
I think that both API define precisely the meaning in  Inputs and Outputs.

"IS-08
The API may be used to define a mapping between one or more audio “Inputs” and one or more audio “Outputs”. Inputs and Outputs are resources local to the device, and as such are not published to the registry. An Input can be assigned audio from an NMOS Receiver, or can represent audio sources from elsewhere (e.g a microphone or physical input). Similarly audio routed to an Output can be assigned to an NMOS Source, or can be consumed elsewhere (e.g be routed to a loudspeaker or a physical output).

IS-11
Input
An Input is a unit consuming media data for providing it to Sender(s). Input may present metadata about media consuming capabilities to its upstream counterpart. Input is a resource and based on Resource Core JSON Schema.

Output
An Output is a unit producing media data provided by Receiver(s). Output may hold metadata about the media consuming capabilities from its downstream counterpart. Output is a resource and based on Resource Core JSON Schema."

Both definitions overlap when IS-08 refer to "or can represent audio sources from elsewhere" and "or can be consumed elsewhere". The associations with Senders and Receivers differ because IS-08 sits between Inputs and Outputs while IS-11 kinds of sits outside.

**Comment by alabou** [comment]
Any conclusion on this issue?

**Comment by garethsb** [comment]
I'm not yet seeing why the device-centric Input / Output terminology couldn't be used in IS-11, but I appreciate I appear to be a lone voice!

**Comment by garethsb** [comment]
A different question related to Inputs and Outputs... In what circumstances are multiple Inputs associated with one Sender?

**Comment by garethsb** [comment]
We discussed this issue in detail on the group call on 31 Jan. Conclusion was the existing names are OK, so long as there is additional explanation of the relationship between IS-11 Inputs and IS-04 Sources, with examples of one Input being related to multiple Sources (and thus Senders, of course) and of multiple Inputs contributing to one Source and/or Sender. Now started in #90.
